### ISSUE TITLE
Feature: Interview field

### ISSUE THREAD

**Issue by oseasmoran73** [januschung/job-winner-ui#17]
## Description

It would be nice to have an interview field in order to track more accurately. Information such as the date, time, and status will help applicants track their apps more accurately.

**Comment by januschung** [comment]
that will require change for db, backend and graphql queries

**Comment by januschung** [comment]
The backend is done and here is the list of function supported:
1. addInterview
2. updateInterview
3. allInterviewByJobApplicationId
4. allInterview (potential use is to get the total count of open interviews that are < time.now())
5. interviewById (use this from the all interview view if updateInterview is not straight forward to be used?)
